server:
  # 设置tomcat
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 50
  # 指定端口
  port: 8080
  # 指定项目的ContextPath路径
  servlet:
    context-path: /lol
    multipart:
      enabled: true
      # 每个文件限制为10M
      max-file-size: 10MB
      # 单次请求所有文件容量不能大于100MB
      max-request-size: 100MB
debug: true
spring:
  # 字符编码过滤器配置（CharacterEncodingFilter）
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 包含dao的yml配置文件,对应的是application-xxx.yml文件的xxx名称
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: true    #页面不加载缓存，修改即时生效
  profiles:
    include: dao
    elasticsearch:
      rest:
        uris: http://127.0.0.1:9200
        connection-timeout: 2s


